security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/agenda/, role: [ROLE_SECRETARIO, ROLE_ADMIN, ROLE_SUPER_ADMIN]}
        - { path: ^/paciente/, role: [ROLE_PODOLOGO, ROLE_ESTUDIANTE, ROLE_PIR,ROLE_ADMIN, ROLE_SUPER_ADMIN]}
        - { path: ^/administracion/, role: [ROLE_ADMIN, ROLE_SUPER_ADMIN]}