
administrar_usuarios:
    path:     /usuarios/
    defaults: { _controller: AppBundle:AdminUsuario:administrarUsuarios }

consultar_usuario:
    path:     /usuarios/{idUsuario}
    defaults: { _controller: AppBundle:AdminUsuario:consultarUsuario }

crear_usuario:
    path:     /usuarios/crear
    defaults: { _controller: AppBundle:AdminUsuario:crearUsuario }

editar_usuario:
    path:     /usuarios/editar
    defaults: { _controller: AppBundle:AdminUsuario:editarUsuario }

habilitar_usuario:
    path:     /usuarios/habilitar
    defaults: { _controller: AppBundle:AdminUsuario:habilitarUsuario }

pre_administrar_logs:
    path:     /logs
    defaults: { _controller: AppBundle:AdminUsuario:preAdministrarLogs }

administrar_logs:
    path:     /logs/administrar
    defaults: { _controller: AppBundle:AdminUsuario:administrarLogs }
    methods: [POST]

consultar_log:
    path:     /logs/{idLog}
    defaults: { _controller: AppBundle:AdminUsuario:consultarLog }

