
administrar_usuarios:
    path:     /usuarios/
    defaults: { _controller: AppBundle:AdminUsuario:administrarUsuarios }

consultar_usuario:
    path:     /usuarios/consultar/{idUsuario}
    defaults: { _controller: AppBundle:AdminUsuario:consultarUsuario }

crear_usuario:
    path:     /usuarios/crear/
    defaults: { _controller: AppBundle:AdminUsuario:crearUsuario }

editar_usuario:
    path:     /{idUsuario}
    defaults: { _controller: AppBundle:AdminUsuario:editarUsuario }
    methods: [GET,POST]

habilitar_usuario:
    path:     /usuarios/habilitar
    defaults: { _controller: AppBundle:AdminUsuario:habilitarUsuario }
    options:
        expose: true

pre_administrar_logs:
    path:     /logs/
    defaults: { _controller: AppBundle:AdminUsuario:preAdministrarLogs }

administrar_logs:
    path:     /logs/administrar/
    defaults: { _controller: AppBundle:AdminUsuario:administrarLogs }

consultar_log:
    path:     /logs/{idLog}
    defaults: { _controller: AppBundle:AdminUsuario:consultarLog }

