agenda_principal:
    path:     /
    defaults: { _controller: AppBundle:Agenda:agendaPrincipal }

consultar_cita:
    path:     /cita/{id}
    defaults: { _controller: AppBundle:Agenda:consultarCita }

nueva_cita:
    path:     /cita/nueva/
    defaults: { _controller: AppBundle:Agenda:nuevaCita }

editar_cita:
    path:     /cita/editar/
    defaults: { _controller: AppBundle:Agenda:editarCita }

eliminar_cita:
    path:     /cita/eliminar/
    defaults: { _controller: AppBundle:Agenda:eliminarCita }

ajustes_agenda:
    path:     /ajustes/
    defaults: { _controller: AppBundle:Agenda:ajustesAgenda }

crear_gabinete:
    path:     /ajustes/gabinete/crear/
    defaults: { _controller: AppBundle:Agenda:crearGabinete }
    methods: [POST]

editar_gabinete:
    path:     /ajustes/gabinete/editar/
    defaults: { _controller: AppBundle:Agenda:editarGabinete }
    methods: [PUT]

habilitar_gabinete:
    path:     /ajustes/gabinete/habilitar/
    defaults: { _controller: AppBundle:Agenda:habilitarGabinete }
    methods: [PUT]
    options:
        expose: true
