consultar_historia_general:
    path:     /historia/general/{idPaciente}
    defaults: { _controller: AppBundle:HistoriaGeneral:consultarHistoriaGeneral }

editar_datos_semipermanentes:
    path:     /semipermanentes/editar/
    defaults: { _controller: AppBundle:HistoriaGeneral:editarDatosSemipermanentes }

crear_datos_semipermanentes:
    path:     /semipermanentes/crear/
    defaults: { _controller: AppBundle:HistoriaGeneral:crearDatosSemipermanentes }

crear_anamnesis:
    path:     /anamnesis/crear
    defaults: { _controller: AppBundle:HistoriaGeneral:crearAnamnesis }

editar_anamnesis:
    path:     /anamnesis/editar
    defaults: { _controller: AppBundle:HistoriaGeneral:editarAnamnesis }

editar_datos_personales:
    path:     /personales/editar/
    defaults: { _controller: AppBundle:HistoriaGeneral:editarDatosPersonales }

crear_datos_personales:
    path:     /personales/crear
    defaults: { _controller: AppBundle:HistoriaGeneral:crearDatosPersonales }

editar_datos_anamnesis:
    path:     /historia/general/datosanamnesis/editar/
    defaults: { _controller: AppBundle:HistoriaGeneral:editarDatosAnamnesis }

crear_datos_anamnesis:
    path:     /historia/general/datosanamnesis/crear/
    defaults: { _controller: AppBundle:HistoriaGeneral:crearDatosAnamnesis }

editar_datos_onicopatis:
    path:     /historia/general/datosonicopatis/editar/
    defaults: { _controller: AppBundle:HistoriaGeneral:editarDatosOnicopatis }

crear_datos_onicopatis:
    path:     /historia/general/datosonicopatis/crear/
    defaults: { _controller: AppBundle:HistoriaGeneral:crearDatosOnicopatis }