dashboard_paciente:
    path:     /{id}
    defaults: { _controller: AppBundle:Paciente:dashboardPaciente }

busqueda_paciente:
    path:     /busqueda/
    defaults: { _controller: AppBundle:Paciente:busquedaPaciente }

crear_paciente:
    path:     /crear/
    defaults: { _controller: AppBundle:Paciente:crearPaciente }

nuevo_paciente:
    path:     /nuevo/
    defaults: { _controller: AppBundle:Paciente:nuevoPaciente }

consultar_historia_complementaria:
    path:     /historia/complementaria/{idPaciente}
    defaults: { _controller: AppBundle:Paciente:consultarHistoriaComplementaria }
    methods: [GET,POST]

crear_historia_complementaria:
    path:     /historia/complementaria/crear/
    defaults: { _controller: AppBundle:Paciente:crearHistoriaComplementaria }
    methods : [POST]

editar_historia_complementaria:
    path:     /historia/complementaria/
    defaults: { _controller: AppBundle:Paciente:editarHistoriaComplementaria }
    methods : [PUT]

eliminar_historia_complementaria:
    path:     /historia/complementaria/eliminar/
    defaults: { _controller: AppBundle:Paciente:eliminarHistoriaComplementaria }

consultar_diagnostico:
    path:     /diagnostico/{idPaciente}
    defaults: { _controller: AppBundle:Paciente:consultarDiagnostico }

crear_diagnostico:
    path:     /diagnostico/crear/
    defaults: { _controller: AppBundle:Paciente:crearDiagnostico }
    options:
        expose: true

nuevo_diagnostico:
    path:     /diagnostico/nuevo/{idPaciente}/{idDiagnostico}
    defaults: { _controller: AppBundle:Paciente:nuevoDiagnostico }

nuevo_diagnostico_sin_param:
    path:     /diagnostico/nuevo/
    defaults: { _controller: AppBundle:Paciente:nuevoDiagnostico }

editar_diagnostico:
    path:     /diagnostico/editar/
    defaults: { _controller: AppBundle:Paciente:editarDiagnostico }
    methods: [POST]
    options:
            expose: true

consultar_pacientes_todos:
    path:       /todos/
    defaults: { _controller: AppBundle:Paciente:todosPacientes }
    options:
        expose: true

consultar_pacientes_filtro:
    path:       /busqueda/filtro/
    defaults: { _controller: AppBundle:Paciente:filtroPacientes }
    options:
        expose: true

consultar_patologias_todos:
    path:       /patologias/
    defaults: { _controller: AppBundle:Paciente:todasPatologias }
    options:
        expose: true

