admin_patologia:
    path:     /
    defaults: { _controller: AppBundle:Patologia:adminPatologias }

crear_patologia:
    path:     /crear
    defaults: { _controller: AppBundle:Patologia:create }

editar_patologia:
    path:     /editar
    defaults: { _controller: AppBundle:Patologia:update }

eliminar_patologia:
    path:     /elimminar
    defaults: { _controller: AppBundle:Patologia:delete }

consultar_patologia:
    path:     /consultar/{idPatologia}
    defaults: { _controller: AppBundle:Patologia:show }
