<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FotoPerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FotoPerfilRepository extends EntityRepository
{

    public function getFotoPerfil($usuario)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        //$q  = $qb->select(array('f'))
        $q = $this->createQueryBuilder('f')

            ->where('f.usuario = :usuario ')
            ->setParameter('usuario',$usuario)
            ->getQuery();

        return $q->getOneOrNullResult();
    }

}
