<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GabineteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GabineteRepository extends EntityRepository
{

    public function getGabinetesActivos()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q = $this->createQueryBuilder('g')
            ->where('g.estado= :estado')
            ->setParameter('estado','Activo')
            ->getQuery();

        return $q->getResult();
    }

}
