<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{

    public function procesarLogAgenda($Subcategoria, $Descripcion, $Paciente,$Usuario){
        $this->procesarLog("Agenda",$Subcategoria,$Descripcion, $Paciente,$Usuario);
    }

    public function procesarLogAdminUsuarios( $Descripcion, $Paciente,$Usuario){
        $this->procesarLog("Administrar","Usuarios",$Descripcion, $Paciente,$Usuario);
    }

    public function procesarLogHistoriaGeneral( $Descripcion, $Paciente,$Usuario){
        $this->procesarLog("Historia","General",$Descripcion, $Paciente,$Usuario);
    }

    public function procesarLogHistoriaComplementaria( $Descripcion, $Paciente,$Usuario){
        $this->procesarLog("Historia","Complementaria",$Descripcion, $Paciente,$Usuario);
    }

    public function procesarLogUsuario($Subcategoria, $Descripcion, $Paciente,$Usuario){
        $this->procesarLog("Usuario",$Subcategoria,$Descripcion, $Paciente,$Usuario);
    }

    public function procesarLogPaciente($Subcategoria, $Descripcion, $Paciente,$Usuario){
        $this->procesarLog("Paciente",$Subcategoria,$Descripcion, $Paciente,$Usuario);
    }

    private function procesarLog( $Categoria, $Subcategoria, $Descripcion, $Paciente,$Usuario){
        $log = new Log();

        $log->setCategoria($Categoria)
            ->setSubcategoria($Subcategoria)
            ->setDescripcion($Descripcion)
            ->setUsuario($Usuario)
            ->setFecha(new \DateTime('now'));
        if($Paciente!=null){
            $log->setPaciente($Paciente);
        }

        $em = $this->getEntityManager();
        $em->persist($log);
        $em->flush();

    }

}
