<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PatPorDiagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatPorDiagRepository extends EntityRepository
{

    public function findPatByIdDiag($idDiagnostico)
    {
        $idDiagnostico = intval($idDiagnostico);
        ld($idDiagnostico);
//
//        return $this->getEntityManager()
//            ->createQueryBuilder()
//            ->select('p')
//            ->from('AppBundle:Patologia', 'p')
//            ->innerJoin('AppBundle:PatologiaPorDiagnostico','pXd')
//            ->where('p.idPatologia = pXd.idPatologia')
//            ->andWhere(' pXd.idDiagnostico = :id')
//            ->setParameter('id', $idDiagnostico)
//            ->getQuery()
//            ->getResult();

        $query = $this->getEntityManager()
            ->createQuery(
                'select p from AppBundle:Patologia p
                join AppBundle:PatologiaPorDiagnostico pXd
                where p.idPatologia = pXd.idPatologia and pXd.idDiagnostico = :id'
            )->setParameter('id', $idDiagnostico)
        ->getResult();
        return $query;

//        $em = $this->getEntityManager();
//        $qb = $em->createQueryBuilder();
//
//        $q  = $qb->select(array('u'))
//            ->from('AppBundle:Patologia', 'u')
//            ->where('u.estado != :estadono ')
//            ->setParameter('estadono','Inhabilitado')
//            ->getQuery();
//
//        return $q->getResult();
    }


}
