<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{

    public function findAllButLD()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q  = $qb->select(array('u'))
            ->from('AppBundle:Usuario', 'u')
            ->where('u.estado != :estadono ')
            ->setParameter('estadono','Inhabilitado')
            ->getQuery();

        return $q->getResult();
    }
}
